### ISSUE TITLE
[@lmc-eu/conventional-changelog-lmc-github] Breaking changes missing from the changelog

### ISSUE THREAD

**Issue by OndraM** [lmc-eu/code-quality-tools#54] opened 2022-02-11 11:53 UTC
The BREAKING CHANGES commits are missing from the generated changelog when using `@lmc-eu/conventional-changelog-lmc-github`.

Which is quite unfortunate :)

**Comment by literat** [comment] 2022-03-29 16:23
Probably caused by #52

**Comment by literat** [comment] 2022-03-31 08:29
Fixed in:
- @lmc-eu/conventional-changelog-lmc-bitbucket@2.0.4
- @lmc-eu/conventional-changelog-lmc-github@2.0.4

**Closed by literat** 2022-03-31 08:29 UTC
Labels: bug
